# Name and metadata of your task
task_name: 'Connexion Livre'
author: 'Cadê VPN 🤷'
description: 'Este é o qualificador para entrar na nossa nova internet - execute esta tarefa para provar que você é um nó confiável e honesto antes de te deixarmos entrar. Precisamos da sua ajuda para manter a internet aberta e livre. || This is the qualifier to join our new internet - run this task to prove you are a reliable and honest node before we let you in. we need your help to keep the internet open and free'
repositoryUrl: 'https://github.com/squidpandabananapants/cadevpn' # Replace with your own repo URL
imageUrl: 'imageUrl'
infoUrl: 'infoUrl'
